# Generated by Django 5.1.14 on 2025-12-02 11:07

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seeds', '0002_tomatovariety_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowDiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('stage', models.CharField(choices=[('sown', 'Sown'), ('germinated', 'Germinated'), ('potted_on', 'Potted on'), ('outdoors', 'Planted outdoors'), ('flowering', 'Flowering'), ('harvest', 'Harvest'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grow_diary_entries', to=settings.AUTH_USER_MODEL)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grow_diary_entries', to='seeds.tomatovariety')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
