# Generated by Django 5.1.14 on 2025-11-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TomatoVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='Used in the URL.', max_length=220, unique=True)),
                ('origin', models.CharField(blank=True, help_text='Where this variety comes from (region, breeder, family, etc.).', max_length=200)),
                ('growth_habit', models.CharField(blank=True, choices=[('indeterminate', 'Indeterminate (cordon)'), ('determinate', 'Determinate (bush)'), ('dwarf', 'Dwarf / compact')], max_length=20)),
                ('days_to_maturity', models.PositiveSmallIntegerField(blank=True, help_text='Approximate days from transplant to ripe fruit (if known).', null=True)),
                ('fruit_color', models.CharField(blank=True, help_text='E.g. red, pink, yellow, striped, black, etc.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short description, flavour notes, and any heritage story.')),
                ('is_featured', models.BooleanField(default=False, help_text='Use to highlight certain varieties on the homepage later.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck if this variety is retired or not currently available.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tomato variety',
                'verbose_name_plural': 'Tomato varieties',
                'ordering': ['name'],
            },
        ),
    ]
