# Generated by Django 5.1.14 on 2025-11-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomatovariety',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tomato_varieties/'),
        ),
    ]
