# Generated by Django 5.1.14 on 2025-11-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('intro', models.TextField(help_text='Short, 1–3 sentence introduction to the recipe.')),
                ('ingredients', models.TextField(help_text='List ingredients, one per line.')),
                ('instructions', models.TextField(help_text='Step-by-step method. Use blank lines to separate steps.')),
                ('prep_time_minutes', models.PositiveIntegerField(blank=True, help_text='Prep time in minutes', null=True)),
                ('cook_time_minutes', models.PositiveIntegerField(blank=True, help_text='Cooking time in minutes', null=True)),
                ('serves', models.PositiveIntegerField(blank=True, help_text='How many people this serves', null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('advanced', 'Advanced')], default='easy', max_length=20)),
                ('is_freezer_friendly', models.BooleanField(default=False)),
                ('is_good_for_gluts', models.BooleanField(default=False, help_text='Tick if this is especially good for using up a glut of tomatoes.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
